name: Micropolitan
favicon: null
layout_spectrum: 0.5527426884509623
typography_spectrum: 0.3064873665571213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3312025920022279
  lightness: 0.9571781021077186
  saturation: 0.4337880543898791
  rhythmicContrast: 0.6713577646296471
purpose: []
